package game.Common.Enum.Network;

public enum TypeOfRequest {
    SIGN_UP ,
    LOGIN ,
    LOGOUT ,
    GET_SCOREBOARD ,
    UPDATE_PROFILE_CHANGE_NICKNAME ,
    UPDATE_PROFILE_CHANGE_PASSWORD ,
    UPDATE_PROFILE_CHANGE_AVATAR ,
    NEW_MESSAGE ,
    NEW_GROUP ,
    HOST_GAME ,
    JOIN_GAME ,
    GET_USER_BY_USERNAME ,
    GET_FRIENDS ,
    SEND_FRIENDSHIP_REQUEST ,
    ACCEPT_FRIENDSHIP_REQUEST ,
    REJECT_FRIENDSHIP_REQUEST ,
    GET_REQUESTS_OF ,
    GET_REQUESTS_FOR ;
}
